### ISSUE TITLE
[Improvement] - Cluster status metrics

### ISSUE THREAD

**Issue by samber** [deadtrickster/prometheus_rabbitmq_exporter#14]
Hi,

Thanks for your work on this project !

Could you please add some metrics about the cluster state ? Especially about partitions ?

**Comment by deadtrickster** [comment]
Hi,

Cluster metrics are on my todo list.

What metrics you want most?

**Comment by samber** [comment]
- cluster size (work around: "up" builtin metric of prometheus)
- number of nodes in the same partitions (for each host)
- number of nodes running a different partition (for each host)

**Comment by deadtrickster** [comment]
Hi

Unfortunately I no longer work with RabbitMQ that close. So will rely on your feedback entirely.

I just added `rabbitmq_nodes_running{name="", type=""} = 1|0` metric. 
Please let me know what you think.

https://github.com/deadtrickster/prometheus_rabbitmq_exporter/releases/tag/rabbitmq-3.6.5.7

**Comment by samber** [comment]
@kyos, if you have spare time :trollface:
