### ISSUE TITLE
Bug: Only one TYPE line may exist for the same metric name

### ISSUE THREAD

**Issue by dnABic** [deadtrickster/prometheus_rabbitmq_exporter#19]
Hi,

I have a cluster of 3 rabbitmq instances. When using prometheus_rabbitmq_exporter version v3.6.5.8 I get the following error on prometheus server side:

`text format parsing error in line 147: second TYPE line for metric name "rabbitmq_nodes_up", or TYPE reported after samples`

The problem seems to be this:

```
# TYPE rabbitmq_nodes_up untyped
# HELP rabbitmq_nodes_up Node runnning status
rabbitmq_nodes_up{name="rabbit@rabbitmq01.example.local",type="disc"} 1
# TYPE rabbitmq_nodes_up untyped
# HELP rabbitmq_nodes_up Node runnning status
rabbitmq_nodes_up{name="rabbit@rabbitmq.example.local",type="disc"} 1
# TYPE rabbitmq_nodes_up untyped
# HELP rabbitmq_nodes_up Node runnning status
rabbitmq_nodes_up{name="rabbit@rabbitmq.example.local",type="disc"} 1

```

while there are 3 TYPE lines for the same metric name, which is in this case rabbitmq_nodes_up.

Similar problem described here: 

https://groups.google.com/forum/#!topic/prometheus-developers/ZVb2NjjUJ5A

Anyways, it seems that it should be printed only once:

```
# TYPE rabbitmq_nodes_up untyped
# HELP rabbitmq_nodes_up Node runnning status

```

instead of 3 times. 

Thanks and Greets!

**Comment by deadtrickster** [comment]
Hi, thanks for the report. Do you need other cluster-related metrics?

**Comment by dnABic** [comment]
Sorry for late reply. I was mostly interested to know how many nodes are in the cluster. But data rates per cluster node would be also very useful. I don't know if it would be possible to detect if there is network partition.

**Comment by deadtrickster** [comment]
What is "data rates"? there are metrics for IO (in bytes) for entire VM.,. or you mean something else?

Re:partitions. I can find a way to transform rabbitmqctl cluster_status. However I thought that rabbitmq_node_up is enough.

**Comment by dnABic** [comment]
I misunderstood data rates. It is actually data volume sent from one cluster node to other cluster nodes in XB/s. I don't find it useful (for me) right now.

I suppose rabbitmq_node_up is enough. I will test it in the next days.

**Comment by deadtrickster** [comment]
please try rabbitmq_node_up and let me know if that works for you. 

Re: data rates. I'm now very confused :-) What you misunderstood and found not useful? Thanks!

**Comment by dnABic** [comment]
RabbitMQ management plugin provides information about data transfer between cluster nodes. On management plugin web interface, this data transfer is called "data rates".
