### ISSUE TITLE
3.6.1: undefined: There is no template at js/tmpl/undefined.ejs

### ISSUE THREAD

**Issue by oneiros-de** [deadtrickster/prometheus_rabbitmq_exporter#2]
I'm trying to install the plugin in a rabbitmq 3.6.1

After enabling the plugins the gui complains about `undefined: There is no template at js/tmpl/undefined.ejs`. How to fix this?

**Comment by deadtrickster** [comment]
Hey,

This should be fixed in rabbitmq 3.6.4
