### ISSUE TITLE
Exporter crashes when a queue is added after plugin initialization

### ISSUE THREAD

**Issue by jperville** [deadtrickster/prometheus_rabbitmq_exporter#22]
# Summary

If a queue is created after the prometheus plugin has initialized, then subsequent called to `/api/metrics` result in "500 internal error". Restarting rabbitmq after still results in "500 internal error" every call to `/api/metrics`.

I encountered the bug with rabbitmq 3.6.8 and 3.6.9, no idea if it applies to earlier versions.

I am using the *.ez files from the latest stable release : https://github.com/deadtrickster/prometheus_rabbitmq_exporter/releases/tag/rabbitmq-3.6.8.1

The nasty stack trace looks like this:
```
=SUPERVISOR REPORT==== 12-Apr-2017::13:52:09 ===
     Supervisor: {local,rabbit_mgmt_db_cache_sup}
     Context:    child_terminated
     Reason:     {badarg,
                     [{dict,fetch,
                          [{resource,unknown,queue,
                               {resource,<<"/">>,queue,<<"boom">>}},
                           {dict,0,16,16,8,80,48,
                               {[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],
                                []},
                               {{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],
                                 []}}}],
                          [{file,"dict.erl"},{line,131}]},
                      {rabbit_mgmt_db,'-list_queue_stats/3-lc$^1/1-1-',4,
                          [{file,"src/rabbit_mgmt_db.erl"},{line,363}]},
                      {rabbit_mgmt_db,list_queue_stats,3,
                          [{file,"src/rabbit_mgmt_db.erl"},{line,360}]},
                      {timer,tc,2,[{file,"timer.erl"},{line,181}]},
                      {rabbit_mgmt_db_cache,handle_call,3,
                          [{file,"src/rabbit_mgmt_db_cache.erl"},{line,107}]},
                      {gen_server,try_handle_call,4,
                          [{file,"gen_server.erl"},{line,615}]},
                      {gen_server,handle_msg,5,
                          [{file,"gen_server.erl"},{line,647}]},
                      {proc_lib,init_p_do_apply,3,
                          [{file,"proc_lib.erl"},{line,247}]}]}
     Offender:   [{pid,<0.613.0>},
                  {id,rabbit_mgmt_db_cache_queues},
                  {mfargs,{rabbit_mgmt_db_cache,start_link,[queues]}},
                  {restart_type,permanent},
                  {shutdown,5000},
                  {child_type,worker}]
```

# How to reproduce

In one terminal, run:
```sh
$ git clone https://github.com/deadtrickster/prometheus_rabbitmq_exporter.git
$ docker build -t dev-rabbitmq .
$ docker run --rm -ti -p 15672:15672 dev-rabbitmq
```

In your web browser:
 - open http://localhost:15672/api/metrics
 - notice that metrics are returned
 - open http://localhost:15672/#/queues
 - unfold the "Add a new queue" link
 - create a queue named "boom" with default attributes (Durable, not AutoDelete)
 - open http://localhost:15672/api/metrics
 - the browser displays an empty page, http status is 500
 - the docker logs displays nasty stack traces like the one above

**Comment by deadtrickster** [comment]
Thank you for the very detailed report. 

https://github.com/deadtrickster/prometheus_rabbitmq_exporter/releases/tag/rabbitmq-3.6.9.1

**Comment by jperville** [comment]
I confirm that the new releases fixes the issue, closing! Thank you very much for the quick fix.
