### ISSUE TITLE
feature request: add hostname or nodename label to metrics

### ISSUE THREAD

**Issue by jperville** [deadtrickster/prometheus_rabbitmq_exporter#23]
I am making an alternative version of your sample grafana dashboard using the metrics exported by this plugin (and related such as prometheus_process_collector), dashboard that I will be happy to share back in a PR.

A problem I have is that the rabbitmq instances are identified by their "instance" label, which is an ephemeral ipaddress and port.

Since I deploy rabbitmq as docker containers inside kubernetes, I would like another label to be added which is more stable than "instance", for example the hostname (of the container) or even better the rabbitmq nodename.

In other words, when I query `process_uptime_seconds` in prometheus, I get:
```
process_uptime_seconds{instance="10.129.0.18:15672",job="kubernetes-service-endpoints",kubernetes_name="rabbitmq",kubernetes_namespace="backends"}	3656
```

I would like to have:
```
process_uptime_seconds{instance="10.129.0.18:15672",nodename="rabbit@rabbitmq-0.rabbitmq-cluster.backends.svc.cluster.local",job="kubernetes-service-endpoints",kubernetes_name="rabbitmq",kubernetes_namespace="backends"}	3656
```

The problem with the "instance" label is that I cannot differentiate:
 - a single rabbitmq instance being redeployed and getting another IP address over time (then I can safely workaround by wrapping the query in `sum (expression) without (instance)`
 - a multi instance rabbitmq cluster where I would like to track the memory usage, file descriptors etc. by nodename

If I don't wrap the data in `sum (expression) without (instance)` then I get "multiple value error" when displaying single stat such as uptime in the dashboard, and I get the same label multiple times in the state displaying the different kind of messages (acknowledged, redelivered etc).

I would also like to templatize the dashboard so that I can check the stats of each rabbitmq node separately in the case of a multi-cluster node.

**Comment by deadtrickster** [comment]
Have you read this? 
https://prometheus.io/docs/concepts/jobs_instances/#automatically-generated-labels-and-time-series

We can just set instance. And by default no one will notice. 
I see it as a config option of the exporter, like ... `{instance, node_name}`. 

Your instance labels are changing dynamically but what about node names? 

-----

And for templating I need to add something like `is_rabbit` so in grafana we can get all instances where is_rabbit is defined.

**Comment by jperville** [comment]
Hello, I did not notice until now the instance label can be configured. Let me play with it and close this issue myself. Thank you very much.

**Comment by jperville** [comment]
I ended up scraping the rabbitmq pods instead of the rabbitmq service, as a consequence I get access to a "kubernetes_pod_name" label which I use in my templating. I am willing to share my modified dashboard as a PR if you are interested.

**Comment by deadtrickster** [comment]
Yes I'm, Thanks!

**Comment by jperville** [comment]
Closing this issue, since I am happy with scraping the rabbitmq pods and using their kubernetes_pod_name as "node" key for the dashboard.
