### ISSUE TITLE
What to use as a target for prometheus?

### ISSUE THREAD

**Issue by oneiros-de** [deadtrickster/prometheus_rabbitmq_exporter#3]
Hi,
after I've deployed the plugins, what should I use as a target for prometheus? `server:8080` gives a `connection refused` and on `server:15672/metrics` the server returns a 404.

Thanks in advance

**Comment by deadtrickster** [comment]
all endpoints managed by management plugin are prefixed with /api so target url for scrapes is server:15672/api/metrics.

**Comment by oneiros-de** [comment]
Thanks.
