### ISSUE TITLE
Error: {plugin_built_with_incompatible_erlang,"prometheus_process_collector"}

### ISSUE THREAD

**Issue by gerhard** [deadtrickster/prometheus_rabbitmq_exporter#30]
Hi,

Would you be willing to re-compile all plugins against R16B03?

RabbitMQ 3.6.x supports R16B03 onwards, so I think that it would make sense for plugins to support the same version as well.

I'm running prometheus_process_collector on 19.3.6.2 and I get `Error: {plugin_built_with_incompatible_erlang,"prometheus_process_collector"}` when enabling the plugin.

Thanks!

**Comment by deadtrickster** [comment]
Hi, 

I'm building everything on the latest version. I guess process_collector error because of NIFs (which looks like a sensible topic and I give instructions for rebuilding).

I think plugins should already support 18 (at least I started developing them on this version). As for R16B03 I can try (and probably will), but given 3.7 ships in 2017 I'm not sure.

Is it your personal need or general requirement for the plugins?
How to distribute builds for different Erlang versions? just upload to releases I guess?

Also, for some reason this plugin listed in devtools, but not in monitoring... should I create a PR?

**Comment by gerhard** [comment]
I would expect that if you were to use R16B03 when compiling all apps required to have Prometheus support in RabbitMQ 3.6, it would be sufficient to just publish the resulting .ez files. I might be wrong when it comes to NIFs, but it's worth trying.

[We build RabbitMQ 3.6.x and all plugins that it ships with on the oldest Erlang version that it supports, R16B03](https://ci-aws.rabbitmq.com/teams/main/pipelines/server-release:v3.6.x?groups=qa%3Apkg). This ensures that anyone with any OTP version from R16B03 to 20.0.5 (latest) can just run RabbitMQ and all Tier 1 plugins.

`prometheus_process_collector` is the first RabbitMQ community plugin that I've come across which prevents me from just dropping the official `.ez` in the plugins dir and have it working. I'm trying to understand the reason behind this inconvenience, and help if I can.

When 3.7 ships:
1. It will support OTP 19.2 + (so this problem with `prometheus_process_collector` will continue)
1. 3.6 will be actively maintained for another 6 months
1. There will continue to be many 3.6 installations for years to come which will be denied easy entry to the Prometheus fun fair via your plugins - it would be a shame 🙂 

PR will be appreciated, definitely.

**Comment by johanneswuerbach** [comment]
@deadtrickster our use-case is adding this plugin to the official docker image like

```
FROM rabbitmq:3.6.12-management

COPY plugins/ /usr/lib/rabbitmq/plugins

RUN rabbitmq-plugins enable accept --offline \
 && rabbitmq-plugins enable prometheus --offline \
 && rabbitmq-plugins enable prometheus_httpd --offline \
 && rabbitmq-plugins enable prometheus_rabbitmq_exporter --offline \
 && rabbitmq-plugins enable prometheus_process_collector --offline
```

which also breaks when starting rabbitmq with the error above.

```
=ERROR REPORT==== 19-Sep-2017::20:02:44 ===
beam/beam_load.c(1287): Error loading module prometheus_process_collector:
  mandatory chunk of type 'Atom' not found



=ERROR REPORT==== 19-Sep-2017::20:02:44 ===
Loading of /var/lib/rabbitmq/mnesia/rabbit@rabbitmq-0-plugins-expand/prometheus_process_collector-1.1.0/ebin/prometheus_process_collector.beam failed: badfile
```

**Comment by johanneswuerbach** [comment]
I'm also getting the same error when running:
`docker run --rm -it deadtrickster/rabbitmq_prometheus:3.6.12`

**Comment by deadtrickster** [comment]
@johanneswuerbach I was compiling on R16B03 and got the same chunk error. Which erlang version you use?

**Comment by johanneswuerbach** [comment]
The one bundled with `rabbitmq:3.6.12-management`

**Comment by deadtrickster** [comment]
I'm now stuck with `erlang:monotonic_time`. This means time_compat must be added to prometheus.erl itself. @gerhard what 3.6.x uses? I found this: https://github.com/rabbitmq/rabbitmq-server/commits/ddd9179c70070c05403ec00abc65298607cb613a/src/time_compat.erl, but it's gone now.

**Comment by gerhard** [comment]
We use https://github.com/rabbitmq/rabbitmq-common/blob/stable/src/time_compat.erl in 3.6.x

**Comment by deadtrickster** [comment]
Ok, I converted maps to records and `monotonic_time` seems to be the last thing to fix. Asked @essen how to do this: https://github.com/processone/p1_utils/blob/master/rebar.config#L4 in erlang.mk. Don't like try-catch really :-)

**Comment by deadtrickster** [comment]
@gerhard Loic said rabbitmq "have a system where the module is recompiled on load depending on the erlang version". How to use that?

**Comment by jcmartins** [comment]
Hi,
I'm compiled it with success for me   **rabbitmq-server-3.6.9-1**

cat /etc/redhat-release 
**CentOS Linux release 7.2.1511 (Core)** 

./rebar3 version
**rebar 3.4.4 on Erlang/OTP 18 Erts 7.2**

rpm -qa |grep erlang
**erlang-18.2-1.el7.centos.x86_64**

libgcc-4.8.5-16.el7.x86_64
**gcc-4.8.5-16.el7.x86_64**

**glibc-2.17-196.el7.x86_64**
glibc-headers-2.17-196.el7.x86_64
glibc-common-2.17-196.el7.x86_64
glibc-devel-2.17-196.el7.x86_64

**Comment by deadtrickster** [comment]
Hi, 
that's expected - OTP 18 supports both maps and erlang:monotonic_time. Glad it works for you anyway!

**Comment by dcorbacho** [comment]
We had to create `time_compat` to support multiple Erlang releases simultaneously, which presented some incompatibilities. For example, before OTP 18 we used `erlang:now/0` to calculate the monotonic time, but from 18 onwards we could use `erlang:monotonic_time/0`.

The `time_compat` module acts as an API for these functions, and the first time any function on the module is called [it recompiles itself](https://github.com/rabbitmq/rabbitmq-common/blob/stable/src/time_compat.erl#L115) and does a dynamic code replacement for the one with the right Erlang version. We do that by replacing the code in `monotonic_time` by the one in `monotonic_time_pre_18` or `monotonic_time_post_18`. Same for all other functions in that module.

So for the code replacement to happen, you need both [time_compat](https://github.com/rabbitmq/rabbitmq-common/blob/stable/src/time_compat.erl) and [code_version](https://github.com/rabbitmq/rabbitmq-common/blob/stable/src/code_version.erl) which is in fact responsible for the code replacement. There is some more documentation on those two modules.

If you depend on `rabbit_common`, you don't need to do anything special to use `time_compat`. The first time it is called (usually during the boot of the node), it will sort out itself.

**Comment by deadtrickster** [comment]
Hi @dcorbacho, 

Thanks! I will use the same "regenerate/cache at first call" technique in the parent library - prometheus.erl. Just one function and I did codegen-based caching using smerl already. 

It will be working on R16B03. Amazing!

**Comment by deadtrickster** [comment]
Please try this:
https://github.com/deadtrickster/prometheus_rabbitmq_exporter/releases/tag/rabbitmq-3.6.12-pre18

Built for R16B03 on Ubuntu (GLIBC 2.24-9ubuntu2.2). Process collector works too!

**Comment by deadtrickster** [comment]
@johanneswuerbach Pushed fixed docker images. They now based on 3.6.12-management too. Thanks for the report.

**Comment by deadtrickster** [comment]
Closing, Thanks for the reports and help!
