### ISSUE TITLE
prometheus_sup.beam failed: badfile

### ISSUE THREAD

**Issue by berendt** [deadtrickster/prometheus_rabbitmq_exporter#32]
I am trying to use the 3.6.12 release of this plugin with the 3.6.12-1 release of RabbitMQ on top of Ubuntu 16.04. Using the Ubuntu packages provided at rabbitmq.com. Erlang version is 18.3.

The required plugins are installed and enabled (``rabbitmq-plugins enable --offline accept prometheus prometheus_httpd prometheus_rabbitmq_exporter``).

The start of rabbitmq-server failed with the following entry in the logs:

```
=ERROR REPORT==== 7-Nov-2017::11:31:29 ===
Loading of /var/lib/rabbitmq/mnesia/rabbit-plugins-expand/prometheus-3.4.0/ebin/prometheus_sup.beam failed: badfile

=ERROR REPORT==== 7-Nov-2017::11:31:29 ===
beam/beam_load.c(1189): Error loading module prometheus_sup:
  mandatory chunk of type 'Atom' not found



=INFO REPORT==== 7-Nov-2017::11:31:29 ===
Error description:
   {could_not_start,prometheus,
       {undef,
           [{prometheus_sup,start_link,[],[]},
            {application_master,start_it_old,4,
                [{file,"application_master.erl"},{line,273}]}]}}
```

**Comment by deadtrickster** [comment]
Hi, this happens because downloaded plug built on OTP 20. Please try this release: https://github.com/deadtrickster/prometheus_rabbitmq_exporter/releases/tag/rabbitmq-3.6.12-pre18

**Comment by berendt** [comment]
@deadtrickster Works. Thank you for the fast reply. Should I add a note to the README file?

**Comment by berendt** [comment]
Tested the ``prometheus_process_collector`` as well. This plugin is now also working.

**Comment by deadtrickster** [comment]
Great! if you think something is missing or unclear please add/change and create PR. Thanks

**Comment by berendt** [comment]
I think a note in the release tag (https://github.com/deadtrickster/prometheus_rabbitmq_exporter/releases/tag/rabbitmq-3.6.12.1) about the minimum require OTP version would be nice. The README file itself looks good to me.

**Comment by deadtrickster** [comment]
Added!
