### ISSUE TITLE
Exporter crashed on RabbitMQ upgrade

### ISSUE THREAD

**Issue by marcdejonge** [deadtrickster/prometheus_rabbitmq_exporter#36]
I've updated RabbitMQ to 3.7.2 and downloaded the latest version of this rabbitmq_exporter, but when calling the metrics endpoint, I get a code 500 error.  In the logging I see the following crash report:

```
2018-01-16 09:58:42.505 [error] <0.30093.30> CRASH REPORT Process <0.30093.30> with 0 neighbours crashed with reason: call to undefined function prometheus_cowboy2_handler:init(#{bindings => #{},body_length => 0,has_body => false,headers => #{...)
2018-01-16 09:58:42.506 [error] <0.30092.30> Ranch listener rabbit_web_dispatch_sup_15672, connection process <0.30092.30>, stream 1 had its request process <0.30093.30> exit with reason undef and stacktrace [{prometheus_cowboy2_handler,init,[#{bindings => #{},body_length => 0,has_body => false,headers => #{...},host => <<"...IP...">>,host_info => undefined,method => <<"GET">>,path => <<"/api/metrics">>,path_info => undefined,peer => {...IP...},pid => <0.30092.30>,port => 15672,qs => <<>>,ref => rabbit_web_dispatch_sup_15672,scheme => <<"http">>,streamid => 1,version => 'HTTP/1.0'},[]],[]},{cowboy_handler,execute,2,[{file,"src/cowboy_handler.erl"},{line,37}]},{cowboy_stream_h,execute,3,[{file,"src/cowboy_stream_h.erl"},{line,205}]},{cowboy_stream_h,request_process,3,[{file,"src/cowboy_stream_h.erl"},{line,184}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]
```

Any idea what this means? I've placed all the plugin files in the correct directory I think. At least it start correctly.

```
[xxx@xx plugins]# pwd
/usr/lib/rabbitmq/plugins
[xxx@xx plugins]# ls -alh
total 492K
drwxr-xr-x 2 root root 4.0K Jan 16 09:38 .
drwxr-xr-x 6 root root 4.0K Jan 14 15:45 ..
-rw-r--r-- 1 root root  14K Nov 21 22:37 accept-0.3.3.ez
-rw-r--r-- 1 root root 195K Dec 21 23:28 prometheus-3.4.5.ez
-rw-r--r-- 1 root root  15K Dec  9 13:07 prometheus_cowboy-0.1.4.ez
-rw-r--r-- 1 root root  21K Nov 21 22:37 prometheus_httpd-2.1.8.ez
-rw-r--r-- 1 root root  18K Dec 21 23:28 prometheus_process_collector-1.3.1.ez
-rw-r--r-- 1 root root 209K Dec 21 23:28 prometheus_rabbitmq_exporter-v3.7.1.1.ez
```

I've also upgraded the plugin by disabling and enabling it.

**Comment by deadtrickster** [comment]
Looks like prometheus_cowboy isn't loaded. could you please try to enable it explicitly?

**Comment by marcdejonge** [comment]
That plugin isn't shown in the plugin list, I only see the prometheus_rabbitmq_exporter.

**Comment by marcdejonge** [comment]
Trying to enable it anyway now resulted in a different message:

`CRASH REPORT Process <0.22456.33> with 0 neighbours crashed with reason: no function clause matching prometheus_http_impl:reply(#{headers => #Fun<prometheus_cowboy2_handler.0.36178297>,path => true,registry => default,standalone => ...}) line 15`

I've now tried to enable the prometheus_httpd plugin, but nothing changes...

**Comment by deadtrickster** [comment]
Maybe you can try to redownload the prometheus_httpd plugin? Looking at the source code - https://github.com/deadtrickster/prometheus-httpd/blob/master/src/prometheus_http_impl.erl#L18 and your crash report I can't tell why map doesn't match. Plus I downloaded ez from release and disassembled prometheus_http_impl.beam and code indeed looks ok.

**Comment by marcdejonge** [comment]
I've removed everything from the directory, disabled the plugin, re-downloaded everything from https://github.com/deadtrickster/prometheus_rabbitmq_exporter/releases/tag/v3.7.1.1 and enabled the plugin again. Now a different error:

`2018-01-16 12:23:42.474 [error] <0.19479.35> CRASH REPORT Process <0.19479.35> with 0 neighbours crashed with reason: call to undefined function prometheus_model_helpers:metric_name(messages_published_total)`

This seems to be from the prometheus plugin, but that one is available. Explicitly enabling it doesn't make a difference.

**Comment by deadtrickster** [comment]
Yes, this module:function is a part of prometheus.erl itself and it's present in the respective prometheus-3.4.5.ez. At this point I would suggest to follow steps from here: https://github.com/deadtrickster/prometheus_rabbitmq_exporter/blob/master/Dockerfile.

**Comment by marcdejonge** [comment]
I've done exactly what you do in the Dockerfile, and this results in the error:

`2018-01-16 12:55:15.933 [error] <0.710.0> CRASH REPORT Process <0.710.0> with 0 neighbours crashed with reason: no case clause matching syncing in prometheus_rabbitmq_queues_collector:'-collect_mf/2-fun-3-'/1 line 75`

I have the feeling that something else is going on. Every time I move the packages, something else is missing...

**Comment by marcdejonge** [comment]
Sorry, just tried again and it now seems to work! Strange...

**Comment by deadtrickster** [comment]
Yeah they all need to be enabled, In 3.7 only "main" plugin shows up in the list. Highly confusing imo.
