### ISSUE TITLE
All rabbitmq_queue_messages_*_total counters always returning 0

### ISSUE THREAD

**Issue by repl-mike-roest** [deadtrickster/prometheus_rabbitmq_exporter#38]
We're using rabbit 3.6.5 with your 3.6.5.9 release and something seems to not be working correctly.

I'm trying to create a grafana dashboard showing publish/delivery rates and all my queue's are always showing 0 (using the standard rabbit management interface I can see there is traffic going through my queues) but the prometheus counters are always showing 0.  

I added a test queue and published a bunch of messages to the queue.  I see the value show in the gauge for ready messages (and other metrics for that queue showing data)
ie:
rabbitmq_queue_messages_ready{vhost="/",queue="test"} 32
rabbitmq_queue_messages{vhost="/",queue="test"} 32
rabbitmq_queue_disk_writes{vhost="/",queue="test"} 32

But all the counters that should allow me to calculate rates are always returning zeros:
rabbitmq_queue_messages_published_total{vhost="/",queue="test"} 0
rabbitmq_queue_messages_delivered_total{vhost="/",queue="test"} 0
....
rabbitmq_queue_messages_returned_total{vhost="/",queue="test"} 0

I have no custom config in rabbitmq.conf for the prometheus_rabbitmq_exporter our enabled plugins are:
[autocluster,prometheus,prometheus_rabbitmq_exporter,rabbitmq_management]

(we're using AWS tag based autoclustering).

Thanks

**Comment by deadtrickster** [comment]
Hi, is this happening on all nodes? can you share your test code?

**Comment by deadtrickster** [comment]
I'll try to look into this on my end really soon. can you just confirm your test code produces expected metric values for just one standalone rabbitmq (i.e. not member of a cluster) in your environment.

**Comment by repl-mike-roest** [comment]
Sounds good I'll do some more testing tomorrow with a single node and see if it returns stats correctly.

**Comment by repl-mike-roest** [comment]
So one thing to note we are running with only
rabbitmq-plugins enable prometheus
rabbitmq-plugins enable prometheus_rabbitmq_exporter

Not the full set you have on the main page as they seemed to not be required.

So I did some single node tests:
[metrics-single-node.txt](https://github.com/deadtrickster/prometheus_rabbitmq_exporter/files/1724008/metrics-single-node.txt)
This was just our AMI spun up with a single node has the same results 0's

[metrics-no-autocluster.txt](https://github.com/deadtrickster/prometheus_rabbitmq_exporter/files/1724006/metrics-no-autocluster.txt)
This I used the same instance and just disabled the autocluster plugin.  Same result 0's

[metrics-no-autocluster-force-reset.txt](https://github.com/deadtrickster/prometheus_rabbitmq_exporter/files/1724007/metrics-no-autocluster-force-reset.txt)
This I used the same instance (with autocluster disabled) and did a force_reset of the rabbit instance and checked again. Same result 0's

[metrics-manual-setup.txt](https://github.com/deadtrickster/prometheus_rabbitmq_exporter/files/1724066/metrics-manual-setup.txt)
This is a blank Ubuntu instance (ami-79873901) manually installing the erlang and rabbitmq packages I linked above, I then manually installed and enabled prometheus and prometheus_rabbitmq_exporter and I'm seeing the exact same behaviour.

**Comment by deadtrickster** [comment]
Thank you. I will have time for debugging this tomorrow and then get back to you.

**Comment by repl-mike-roest** [comment]
Sounds good Here's the full script I used to install/configure rabbit in that last setup:

#!/usr/bin/env bash

#update packages
apt-get -y update
DEBIAN_FRONTEND=noninteractive apt-get -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" dist-upgrade

# Install rabbitmq with specific version
echo "Installing erlang"
wget http://packages.erlang-solutions.com/site/esl/esl-erlang/FLAVOUR_1_general/esl-erlang_19.0-1~ubuntu~xenial_amd64.deb -O esl-erlang_19.0-1~ubuntu~xenial_amd64.deb && dpkg -i esl-erlang_19.0-1~ubuntu~xenial_amd64.deb

echo 'Installing erlang dependencies'
DEBIAN_FRONTEND=noninteractive apt-get -f -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" install

# Stop auto updating when apt-get dist-upgrade is called
apt-mark hold esl-erlang

echo "Installing rabbitmq 3.6.5"
wget https://www.rabbitmq.com/releases/rabbitmq-server/v3.6.5/rabbitmq-server_3.6.5-1_all.deb -O rabbitmq-3.6.5.deb && dpkg -i rabbitmq-3.6.5.deb

set -euf -o pipefail

# Install dependencies
echo 'Installing rabbit dependencies'
DEBIAN_FRONTEND=noninteractive apt-get -f -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" install

# Stop auto updating when apt-get dist-upgrade is called
apt-mark hold rabbitmq-server

echo 'Initializing rabbit plug in manager'
rabbitmq-plugins enable rabbitmq_management

wget https://github.com/deadtrickster/prometheus_rabbitmq_exporter/releases/download/rabbitmq-3.6.5.9/prometheus-3.1.0.ez
wget https://github.com/deadtrickster/prometheus_rabbitmq_exporter/releases/download/rabbitmq-3.6.5.9/prometheus_rabbitmq_exporter-v3.6.5.9.ez

mv prometheus-3.1.0.ez /usr/lib/rabbitmq/lib/rabbitmq_server-3.6.5/plugins/
mv prometheus_rabbitmq_exporter-v3.6.5.9.ez /usr/lib/rabbitmq/lib/rabbitmq_server-3.6.5/plugins/

rabbitmq-plugins enable prometheus
rabbitmq-plugins enable prometheus_rabbitmq_exporter

rabbitmqctl add_user rabbitmq Password123
rabbitmqctl set_user_tags rabbitmq administrator
rabbitmqctl set_permissions rabbitmq ".*" ".*" ".*"

service rabbitmq-server restart

**Comment by deadtrickster** [comment]
Please try this (do not forget to rename to .ez). Actually this is a bug that was fixed here later, starting from 3.6.8 branch. If it works I'll replace plugin in respective releases.

[prometheus_rabbitmq_exporter-v3.6.5.9.zip](https://github.com/deadtrickster/prometheus_rabbitmq_exporter/files/1727611/prometheus_rabbitmq_exporter-v3.6.5.9.zip)

**Comment by repl-mike-roest** [comment]
Hmm I put that in and got when trying to boot the cluster

=INFO REPORT==== 15-Feb-2018::14:00:34 ===
Error description:
   {error,{missing_dependencies,[prometheus],
                                [prometheus_rabbitmq_exporter,
                                 prometheus_rabbitmq_exporter]}}

Log files (may contain more information):
   /var/log/rabbitmq/rabbit@ip-10-31-70-30.log
   /var/log/rabbitmq/rabbit@ip-10-31-70-30-sasl.log

Stack trace:
   [{rabbit_plugins,ensure_dependencies,1,
                    [{file,"src/rabbit_plugins.erl"},{line,176}]},
    {rabbit_plugins,prepare_plugins,1,
                    [{file,"src/rabbit_plugins.erl"},{line,195}]},
    {rabbit,broker_start,0,[{file,"src/rabbit.erl"},{line,280}]},
    {rabbit,start_it,1,[{file,"src/rabbit.erl"},{line,403}]},
    {init,start_em,1,[]},
    {init,do_boot,3,[]}]

ubuntu@ip-10-31-70-30:/var/log/rabbitmq$ ls -la /usr/lib/rabbitmq/lib/rabbitmq_server-3.6.5/plugins/prometh*
-rw-rw-r-- 1 ubuntu ubuntu 193726 Feb 12 20:15 /usr/lib/rabbitmq/lib/rabbitmq_server-3.6.5/plugins/prometheus-3.1.0.ez
-rw-rw-r-- 1 ubuntu ubuntu 194256 Feb 15 12:31 /usr/lib/rabbitmq/lib/rabbitmq_server-3.6.5/plugins/prometheus_rabbitmq_exporter-v3.6.5.9.ez

So the files exist.

**Comment by repl-mike-roest** [comment]
Ok nevermind I got it working.  And now the stats are reporting correctly.

**Comment by deadtrickster** [comment]
I updated plugin on the release page. Thanks you for the help!
