### ISSUE TITLE
Windows - crash enabling prometheus_process_collector

### ISSUE THREAD

**Issue by kfreem02** [deadtrickster/prometheus_rabbitmq_exporter#39]
Using Windows Server 2012 R2, rabbitmq 3.6.15, erlang OTP 20.2, with plugins from 3.6.14.1 release.  Get the following error in console when enabling the plugin.  Rabbitmq is installed as a service and the user which runs the service has full control of the plugin expand directory.

C:\Program Files (x86)\RabbitMQ Server\rabbitmq_server-3.6.15\sbin>rabbitmq-plugins.bat enable prometheus_process_collector
The following plugins have been enabled:
  prometheus_process_collector

Applying plugin configuration to rabbit@MYQUEPP1... failed.
Error: {plugin_module_unloadable,"prometheus_process_collector",
                                 {error,on_load_failure}}

I am unable to restart rabbitmq if the plugin is in enabled status.  The following is generated in the rabbitmq.log:
=WARNING REPORT==== 27-Feb-2018::13:24:12 ===
The on_load function for module prometheus_process_collector returned:
{error,{load_failed,"Failed to load NIF library c:/Users/MYRAB~1/AppData/Roaming/RabbitMQ/db/rabbit@MYQUEPP1-plugins-expand/prometheus_process_collector-1.3.0/priv/prometheus_process_collector: 'The specified module could not be found.'"}}

=INFO REPORT==== 27-Feb-2018::13:24:12 ===
Error description:
  {plugin_module_unloadable,"prometheus_process_collector",
                            {error,on_load_failure}}

Log files (may contain more information):
  D:/Logs/rabbit@MYQUEPP1.log
  D:/Logs/rabbit@MYQUEPP1-sasl.log

Stack trace:
  [{rabbit_plugins,prepare_dir_plugin,1,
                   [{file,"src/rabbit_plugins.erl"},{line,249}]},
   {rabbit_plugins,'-prepare_plugins/1-lc$^0/1-0-',2,
                   [{file,"src/rabbit_plugins.erl"},{line,213}]},
   {rabbit_plugins,prepare_plugins,1,
                   [{file,"src/rabbit_plugins.erl"},{line,213}]},
   {rabbit,broker_start,0,[{file,"src/rabbit.erl"},{line,300}]},
   {rabbit,start_it,1,[{file,"src/rabbit.erl"},{line,424}]},
   {init,start_em,1,[{file,"init.erl"},{line,1085}]},
   {init,do_boot,3,[{file,"init.erl"},{line,793}]}]

**Comment by kfreem02** [comment]
I also tried replacing only the prometheus_process_collector plugin with version 1.1.0 and receive the same errors.

**Comment by deadtrickster** [comment]
Hi, unfortunately process collector currently supports Linux, OSX, and FreeBSD, but not Windows.

**Comment by deadtrickster** [comment]
Closing this issue, if you'd like you can watch https://github.com/deadtrickster/prometheus_process_collector repo, hopefully it'll get Windows support at some point.
