### ISSUE TITLE
Possible to require authentication for `/api/metrics`?

### ISSUE THREAD

**Issue by ELundby45** [deadtrickster/prometheus_rabbitmq_exporter#43]
I'm noticing locally I'm able to hit the `/api/metrics` endpoint without being authenticated to the RabbitMQ management portal. 

Is there a way to use the basic auth for this endpoint that the RabbitMQ management plugin provides?

**Comment by deadtrickster** [comment]
Currently it's not possible to reuse management auth. However, you can still configure authentication via `prometheus` app `prometheus_http` env key:

```erlang
{prometheus,
 [{prometheus_http, [{authorization,
                      {basic, "qwe", "qwa"}}]}]}
```

**Comment by cookandy** [comment]
Hello,

I'm having some trouble using basic auth.  I have tried

```
  {prometheus, [
    {prometheus_http, [{authorization, {basic, "user", "pass"}}]},
    {rabbitmq_exporter, [
      {path, "/prometheus"},
      {connections_total_enabled, true}
    ]}
  ]}
```

as well as 

```
  {prometheus, [
    {rabbitmq_exporter, [
      {path, "/prometheus"},
      {connections_total_enabled, true}
    ]},
    {prometheus_http, [{authorization, {basic, "user", "pass"}}]}
  ]}
```

But they both result in a `403 Forbidden` when trying to connect with basic auth

```
❯  curl -v -k https://rabbitmq.myhost.mydomain:15671/api/prometheus --user user:pass
*   Trying ...
........
........
*  SSL certificate verify ok.
* Server auth using Basic with user 'user'
> GET /api/prometheus HTTP/1.1
> Host: rabbitmq.myhost.mydomain:15671
> Authorization: Basic dXNlcjpwYXNz
> User-Agent: curl/7.54.0
> Accept: */*
>
< HTTP/1.1 403 Forbidden
< server: Cowboy
< date: Fri, 13 Jul 2018 15:54:49 GMT
< content-length: 0
<
* Connection #0 to host rabbitmq.myhost.mydomain left intact
```

Can you please tell me what I'm doing wrong?  Thanks!

**Comment by deadtrickster** [comment]
Hi, I'll look into this shortly

**Comment by cookandy** [comment]
Hi @deadtrickster - thanks for the reply!

I'm using `https` for my RMQ mgmt port - not sure if that matters.

```
  {rabbitmq_management, [
    {listener, [{port, 15671},
                {ssl, true},
                {ssl_opts, [{cacertfile,"/etc/ssl/server.crt"},
                    {certfile,"/etc/ssl/server.crt"},
                    {keyfile,"/etc/ssl/server.key"}


                    ]}
              ]}
  ]},
```

I'm also using RMQ version `3.6.8`.  Are you able to reproduce using these settings?

**Comment by deadtrickster** [comment]
added in master and here https://github.com/deadtrickster/prometheus_rabbitmq_exporter/releases/tag/v3.7.2.3
