### ISSUE TITLE
Be a good RabbitMQ 3.7.x plugin citizen: depend on the `rabbit` app

### ISSUE THREAD

**Issue by michaelklishin** [deadtrickster/prometheus_rabbitmq_exporter#44]
Starting with 3.7.x plugins [must depend on the `rabbit` app](https://github.com/rabbitmq/rabbitmq-server/releases/tag/v3.7.0) (see Breaking Changes: apparently I cannot link to a section, sorry) or else they won't [appear in `rabbitmq-plugins list` output](https://groups.google.com/forum/#!topic/rabbitmq-users/ay0rGo5Ccv4).

This is not an issue if the plugin is "pre-enabled" (was enabled previously or the node uses a generated `enabled_plugins` file) but it is a major problem for beginners.

**Comment by deadtrickster** [comment]
Hey, thanks for pointing out but I don't get what 'depend' means, I have rabbit listed there https://github.com/deadtrickster/prometheus_rabbitmq_exporter/blob/master/src/prometheus_rabbitmq_exporter.app.src#L9. Could you please elaborate.

**Comment by michaelklishin** [comment]
Oh, so there is a hand crafted `.app.src` file. Fair enough, sorry about the noise.
