### ISSUE TITLE
Error when enabling prometheus_cowboy on 3.6.10

### ISSUE THREAD

**Issue by rafaelmagu** [deadtrickster/prometheus_rabbitmq_exporter#46]
I am in the process of setting up an Ubuntu Bionic (18.04) RabbitMQ cluster, and am trying to get this exporter working. The APT repos for this distro have RabbitMQ 3.6.x instead of 3.7.x, and it may be why it's showing me an error when enabling `prometheus_cowboy`.

The releases page for the 3.6.x branch of this plugin don't have a binary for `prometheus_cowboy`. I can see `cowboy` is already an enabled plugin in the default RabbitMQ install.

Should I just remove the `rabbitmq-plugins enable --offline prometheus_cowboy` from my setup?

**Comment by deadtrickster** [comment]
Yes you shouldn't enable prometheus_cowboy! I also think you could try official rabbitmq repository instead of Ubuntu. http://www.rabbitmq.com/install-debian.html

**Comment by rafaelmagu** [comment]
Indeed, I am using RabbitMQ's official repos, but they haven't been updated yet for `bionic`. They acknowledged that now. I will update my setup to exclude the `prometheus_cowboy` line.
