### ISSUE TITLE
prometheus_process_collector failed to load due to bad_lib version on ubuntu 14.04

### ISSUE THREAD

**Issue by cristicalin** [deadtrickster/prometheus_rabbitmq_exporter#5]
I upgraded a rabbitmq cluster (3 nodes) from version 3.3.5 to version 3.6.5 in order to use the prometheus exporter. After the upgrade I managed to enable the prometheus_rabbitmq_exporter and prometheus plugins but the prometheus_process_collector plugin fails to load with the following error.

=WARNING REPORT==== 24-Aug-2016::13:24:15 ===
The on_load function for module prometheus_process_collector returned {error,
                                                                       {bad_lib,
                                                                        "Library version (2.11) not compatible (with 2.4)."}}

**Comment by deadtrickster** [comment]
Process collector is based on NIFs and I built it on Ubuntu 16. Unfortunately right now it means you have to rebuild it yourself as I don't have resources for maintaining different binary versions. 

Rebar3 can't build ez archive but it's just a zip archive of ebin/ and priv/ folders (http://erlang.org/doc/man/code.html see "Loading of Code From Archive Files").

Sorry for the inconvenience.

**Comment by cristicalin** [comment]
Do you have any guidelines on how to build it on Ubuntu ?
I tried with both 14.04 and 16.04 and I can't get a working build, on 16.04 I only get a priv/ folder, no ebin/ and on 14.04 it fails to build with the following errors:

root@51938d082d0d:~/prometheus_process_collector# ./rebar3 compile
===> Verifying dependencies...
===> Compiling prometheus
===> Compiling /root/prometheus_process_collector/_build/default/lib/prometheus/src/model/prometheus_model.erl failed
/root/prometheus_process_collector/_build/default/lib/prometheus/src/model/prometheus_model.erl:2012: attribute 'dialyzer' after function definitions
/root/prometheus_process_collector/_build/default/lib/prometheus/src/model/prometheus_model.erl:2026: attribute 'dialyzer' after function definitions
/root/prometheus_process_collector/_build/default/lib/prometheus/src/model/prometheus_model.erl:2048: attribute 'dialyzer' after function definitions
/root/prometheus_process_collector/_build/default/lib/prometheus/src/model/prometheus_model.erl:2057: attribute 'dialyzer' after function definitions
/root/prometheus_process_collector/_build/default/lib/prometheus/src/model/prometheus_model.erl:2070: attribute 'dialyzer' after function definitions
/root/prometheus_process_collector/_build/default/lib/prometheus/src/model/prometheus_model.erl:2092: attribute 'dialyzer' after function definitions
/root/prometheus_process_collector/_build/default/lib/prometheus/src/model/prometheus_model.erl:2101: attribute 'dialyzer' after function definitions
/root/prometheus_process_collector/_build/default/lib/prometheus/src/model/prometheus_model.erl:2110: attribute 'dialyzer' after function definitions
/root/prometheus_process_collector/_build/default/lib/prometheus/src/model/prometheus_model.erl:2123: attribute 'dialyzer' after function definitions
/root/prometheus_process_collector/_build/default/lib/prometheus/src/model/prometheus_model.erl:2159: attribute 'dialyzer' after function definitions
/root/prometheus_process_collector/_build/default/lib/prometheus/src/model/prometheus_model.erl:2182: attribute 'dialyzer' after function definitions
/root/prometheus_process_collector/_build/default/lib/prometheus/src/model/prometheus_model.erl:2193: attribute 'dialyzer' after function definitions
/root/prometheus_process_collector/_build/default/lib/prometheus/src/model/prometheus_model.erl:2204: attribute 'dialyzer' after function definitions
/root/prometheus_process_collector/_build/default/lib/prometheus/src/model/prometheus_model.erl:2216: attribute 'dialyzer' after function definitions
/root/prometheus_process_collector/_build/default/lib/prometheus/src/model/prometheus_model.erl:2228: attribute 'dialyzer' after function definitions
/root/prometheus_process_collector/_build/default/lib/prometheus/src/model/prometheus_model.erl:2237: attribute 'dialyzer' after function definitions

Any hints would be greatly appreciated.

**Comment by deadtrickster** [comment]
Hey, 

Quick googling suggests you need to update your Erlang/OTP distribution to 18+.

**Comment by cristicalin** [comment]
Seems that it works if I just swap the erlang environment for the one at https://www.erlang-solutions.com/resources/download.html
Tested it with version 19 and rabbitmq 3.6.5 and your release binaries work, no need for a recompile.
You might want to add a note about that minimum erlang/otp version 18 requirement and how to get it on ubuntu 14.04, I guess there's a lot of people still relying on 14.04 and might find this useful.

Thanks for the help and for a great tool!

**Comment by deadtrickster** [comment]
Glad you solved the problem!

I'll definitely note that in the README.

I believe this issue can be closed?

**Comment by cristicalin** [comment]
Yes, closing the issue.
