### ISSUE TITLE
Which version of Prometheus RabbitMQ Exporter should I choose for which RabbitMQ version?

### ISSUE THREAD

**Issue by laimison** [deadtrickster/prometheus_rabbitmq_exporter#65]
I'm looking for Prometheus plugin for RabbitMQ 3.3.5. Do you know which version is suitable for this? Actually I'm willing to automate dependencies downloading for any RabbitMQ version to ensure that Prometheus is enabled and compatible to avoid manual work. Any hints on that? I'm having some difficulties to find older plugins.

Many thanks

**Comment by deadtrickster** [comment]
I started this plugin with 3.6.x in mind. So the very first release is for this version. You could try it though.

**Comment by laimison** [comment]
@deadtrickster , thanks a lot for the answer and a great plugin. We will upgrade RabbitMQ. As I mentioned I'm willing to automate dependency resolution. The script should check RabbitMQ version and ensure that right Prometheus version is downloaded (if possible). How do I identify in the future which RabbitMQ version is suitable to which Prometheus version? As I see these dependencies are required, but not sure how to understand versioning for:

get accept-0.3.3.ez
get prometheus-3.5.1.ez
get prometheus_cowboy-0.1.4.ez
get prometheus_httpd-2.1.8.ez
get prometheus_process_collector-1.3.1.ez
get prometheus_rabbitmq_exporter-3.7.2.3.ez
