### ISSUE TITLE
Unable to install Prometheus - dependency prometheus_httpd

### ISSUE THREAD

**Issue by davlind87** [deadtrickster/prometheus_rabbitmq_exporter#67]
Hi, 

I tried to install Prometheus according to the RAEDME. But stubble upon a dependency issue even if the file (prometheus_httpd) is precence in the /plugins/ folder. 

Error:
{error,{missing_dependencies,[accept],[prometheus_httpd]}}
 Stacktrace [{rabbit_plugins,ensure_dependencies,1,
                 [{file,"src/rabbit_plugins.erl"},{line,27
             {'Elixir.RabbitMQ.CLI.Plugins.Helpers',list,1
                 [{file,"lib/rabbitmq/cli/plugins/plugins_
                  {line,49}]},
             {'Elixir.RabbitMQ.CLI.Plugins.Helpers',valida
                 [{file,"lib/rabbitmq/cli/plugins/plugins_
                  {line,121}]},
             {'Elixir.RabbitMQ.CLI.Plugins.Commands.Enable
                 [{file,"lib/rabbitmq/cli/plugins/commands
                  {line,74}]},
             {'Elixir.RabbitMQCtl',maybe_run_command,3,
                 [{file,"lib/rabbitmqctl.ex"},{line,106}]}
             {'Elixir.RabbitMQCtl','-exec_command/2-fun-0-
                 [{file,"lib/rabbitmqctl.ex"},{line,73}]},
             {'Elixir.RabbitMQCtl',main,1,
                 [{file,"lib/rabbitmqctl.ex"},{line,36}]},
             {'Elixir.Kernel.CLI','-exec_fun/2-fun-0-',3,
                 [{file,"lib/kernel/cli.ex"},{line,105}]}]

I cannot even enable this plugin solo without getting the same error message. 

Any thoughts?

Thanks for support!

**Comment by davlind87** [comment]
Missed "accept.ez" plugin. Works fine now.

**Comment by gerhard** [comment]
FWIW, there's this on rabbitmq.com: https://www.rabbitmq.com/prometheus.html
