### ISSUE TITLE
missing some rabbitmq metrics

### ISSUE THREAD

**Issue by expanderbolt** [deadtrickster/prometheus_rabbitmq_exporter#69]
I have installed the rabbitmq_exporter in a cluster of two rabbitmq v3.7.10 servers. I can get most of the metrics through my prometheus servers, however Im missing a few like those starting with rabbitmq_queue_*.
There is no load on the servers and there are no queues configured but the metrics should show up anyway with value zero or?
Output of rabbitmq-plugins list:

Listing plugins with pattern ".*" ...
 Configured: E = explicitly enabled; e = implicitly enabled
 | Status: * = running on rabbit@x.x.x.x
 |/
[E*] prometheus_rabbitmq_exporter      3.7.2.3
[  ] rabbitmq_amqp1_0                  3.7.10
[  ] rabbitmq_auth_backend_cache       3.7.10
[  ] rabbitmq_auth_backend_http        3.7.10
[  ] rabbitmq_auth_backend_ldap        3.7.10
[  ] rabbitmq_auth_mechanism_ssl       3.7.10
[  ] rabbitmq_consistent_hash_exchange 3.7.10
[E*] rabbitmq_delayed_message_exchange 20171201-3.7.x
[  ] rabbitmq_event_exchange           3.7.10
[  ] rabbitmq_federation               3.7.10
[  ] rabbitmq_federation_management    3.7.10
[  ] rabbitmq_jms_topic_exchange       3.7.10
[e*] rabbitmq_management               3.7.10
[e*] rabbitmq_management_agent         3.7.10
[  ] rabbitmq_mqtt                     3.7.10
[E*] rabbitmq_peer_discovery_aws       3.7.10
[e*] rabbitmq_peer_discovery_common    3.7.10
[  ] rabbitmq_peer_discovery_consul    3.7.10
[  ] rabbitmq_peer_discovery_etcd      3.7.10
[  ] rabbitmq_peer_discovery_k8s       3.7.10
[  ] rabbitmq_random_exchange          3.7.10
[  ] rabbitmq_recent_history_exchange  3.7.10
[  ] rabbitmq_sharding                 3.7.10
[E*] rabbitmq_shovel                   3.7.10
[E*] rabbitmq_shovel_management        3.7.10
[  ] rabbitmq_stomp                    3.7.10
[  ] rabbitmq_top                      3.7.10
[  ] rabbitmq_tracing                  3.7.10
[  ] rabbitmq_trust_store              3.7.10
[e*] rabbitmq_web_dispatch             3.7.10
[  ] rabbitmq_web_mqtt                 3.7.10
[  ] rabbitmq_web_mqtt_examples        3.7.10
[  ] rabbitmq_web_stomp                3.7.10
[  ] rabbitmq_web_stomp_examples       3.7.10

**Comment by deadtrickster** [comment]
If you have no queues, metrics will be value-less. Just name and help string. You can  check your metrics endpoint.

**Comment by expanderbolt** [comment]
I started some performance tests and the metrics showed up. Thanks
