### ISSUE TITLE
rabbitmq_queue_consumer_utilisation defaults to empty, should default to 0.0

### ISSUE THREAD

**Issue by oneiros-de** [deadtrickster/prometheus_rabbitmq_exporter#7]
With the last version I get errors by prometheus:
`text format parsing error in line 1589: expected float as value, got "''"`

The offending line is 
`rabbitmq_queue_consumer_utilisation{vhost="hermesmo",queue="rejectedMessagesQueue"} ''`
The queues haven't got any traffic yet.

**Comment by deadtrickster** [comment]
Sorry about that! I hope I'll fix it soon.

**Comment by deadtrickster** [comment]
Hmm so RabbitMQ sets utilization to '' and I render it as NaN now. Please download prometheus_rabbitmq_exporter again. https://github.com/deadtrickster/prometheus_rabbitmq_exporter/releases/download/rabbitmq-3.6.5.3/prometheus_rabbitmq_exporter-v3.6.5.3.ez

**Comment by deadtrickster** [comment]
So does it work for you know?

**Comment by deadtrickster** [comment]
I'm closing this issue. Feel free to reopen if the problem persists.

**Comment by oneiros-de** [comment]
Thanks, it works now.
